version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      cargo-compatible:
        update-types: [minor, patch]
  - package-ecosystem: nuget
    directory: /winui
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      nuget-compatible:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      actions-compatible:
        update-types: [minor, patch]
