[package]
name = "r-helper"
version = "0.8.7"
edition = "2024"
description = "R-Helper - Razer Blade control interface"
authors = ["Fatalution"]

[[bin]]
name = "rhelper"
path = "src/main.rs"

[dependencies]
eframe = "0.33.3"
anyhow = "1.0.89"
librazer = { path = "./librazer" }
image = "0.25.8"
strum = { version = "0.28.0", features = ["derive"] }
tray-icon = "0.21.1"
raw-window-handle = "0.6.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

[target.'cfg(windows)'.dependencies]
app-single-instance = "0.1"
winreg = "0.56"
wmi = "0.18.4"
nvml-wrapper = "0.12.1"
windows-future = { version = "0.3.2", features = ["std"] }
windows = { version = "0.62.0", features = [
    "Devices_Bluetooth",
    "Devices_Enumeration",
    "Foundation",
    "Foundation_Collections",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_Properties",
    "Win32_Foundation",
    "Win32_Storage_EnhancedStorage",
    "Win32_Storage_FileSystem",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_LibraryLoader",
    "Win32_System_Power",
    "Win32_System_StationsAndDesktops",
    "Win32_System_Variant",
    "Win32_UI_Shell",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
embed-resource = "3.0.9"

[workspace]
resolver = "3"
members = [
    ".",          # r-helper (GUI)
    "librazer",   # shared lib
]
default-members = [
    ".",          # build only the GUI by default (root crate)
]

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
