[package]
name = "librazer"
version = "0.10.1"
edition = "2024"
license = "MIT"
description = "Razer laptop and Cooling Pad protocols for R-Helper Compact"
repository = "https://github.com/e-khurmamatov/r-helper-compact"
publish = false
readme = "../README.md"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
const-str = "1.1"
const_format = "0.2.32"
hidapi = {version = "2.6.1", features = ["windows-native"]}
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
strum = "0.28.0"
strum_macros = "0.28.0"

[target.'cfg(windows)'.dependencies]
winreg = { version = "0.56", features = ["transactions"] }

[build-dependencies]
serde_json = "1.0.114"
